library(ISLR)
library(tree)
mydata=read.csv("C:/Users/Naveen/Desktop/final.csv")
high=ifelse(mydata$DAY_OF_WEEK>=4,"MORE","LESS")
mydata=data.frame(mydata,high)
names(mydata)
mydata=mydata[-3]
set.seed(5)
train=sample(1:nrow(mydata),nrow(mydata)/265)
test=-train
training_data=mydata[train,]
testing_data=mydata[test,]
tree_model=tree(high~.,training_data)
tree_model
plot(tree_model)
text(tree_model,pretty=0)
test_pred=predict(tree_model,testing_data,type="class")
testing_high=high[test]
mean(test_pred!=testing_high)
set.seed(3)
cv_tree=cv.tree(tree_model,FUN=prune.misclass)
names(cv_tree)
plot(cv_tree$size,cv_tree$dev,type="b")
pruned_model=prune.misclass(tree_model,best=2)
text(pruned_model,pretty=0)
tree_pred=predict(pruned_model,testing_data,type="class")
mean(tree_pred!=testing_high)
